[build]
  command = "npm run build"
  publish = "build"

# Tell Netlify NOT to block deploys because of Firebase's public API key
[build.environment]
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIza"
